import { Figure } from './figure';

export type TextStyle = { text: string; size: number };
type ProfileText = { [key in Figure]: TextStyle };

const DSize = 24; // default font size
const BSize = 18; // bid font size

export const FigureText: ProfileText = {
    [Figure._0]: { text: '0', size: DSize },
    [Figure._1]: { text: '1', size: DSize },
    [Figure._2]: { text: '2', size: DSize },
    [Figure._3]: { text: '3', size: DSize },
    [Figure._4]: { text: '4', size: DSize },
    [Figure._5]: { text: '5', size: DSize },
    [Figure._6]: { text: '6', size: DSize },
    [Figure._7]: { text: '7', size: DSize },
    [Figure._8]: { text: '8', size: DSize },
    [Figure._9]: { text: '9', size: DSize },
    [Figure._10]: { text: '10', size: DSize },
    [Figure._11]: { text: '11', size: DSize },
    [Figure._12]: { text: '12', size: DSize },
    [Figure._13]: { text: '13', size: DSize },
    [Figure._14]: { text: '14', size: DSize },
    [Figure._15]: { text: '15', size: DSize },
    [Figure._16]: { text: '16', size: DSize },
    [Figure._17]: { text: '17', size: DSize },
    [Figure._18]: { text: '18', size: DSize },
    [Figure._19]: { text: '19', size: DSize },
    [Figure._20]: { text: '20', size: DSize },
    [Figure._21]: { text: '21', size: DSize },
    [Figure._22]: { text: '22', size: DSize },
    [Figure._23]: { text: '23', size: DSize },
    [Figure._24]: { text: '24', size: DSize },
    [Figure._25]: { text: '25', size: DSize },
    [Figure._26]: { text: '26', size: DSize },
    [Figure._27]: { text: '27', size: DSize },
    [Figure._28]: { text: '28', size: DSize },
    [Figure._29]: { text: '29', size: DSize },
    [Figure._30]: { text: '30', size: DSize },
    [Figure._31]: { text: '31', size: DSize },
    [Figure._32]: { text: '32', size: DSize },
    [Figure._33]: { text: '33', size: DSize },
    [Figure._34]: { text: '34', size: DSize },
    [Figure._35]: { text: '35', size: DSize },
    [Figure._36]: { text: '36', size: DSize },
    [Figure._1ST12]: { text: '1st12', size: DSize },
    [Figure._2ND12]: { text: '2nd12', size: DSize },
    [Figure._3RD12]: { text: '3rd12', size: DSize },
    [Figure._1TO18]: { text: '1-18', size: DSize },
    [Figure._19TO36]: { text: '19-36', size: DSize },
    [Figure._1_LINE]: { text: '2to1', size: DSize },
    [Figure._2_LINE]: { text: '2to1', size: DSize },
    [Figure._3_LINE]: { text: '2to1', size: DSize },
    [Figure.EVEN]: { text: 'EVEN', size: DSize },
    [Figure.ODD]: { text: 'ODD', size: DSize },
    [Figure.RED]: { text: 'RED', size: DSize },
    [Figure.BLACK]: { text: 'BLACK', size: DSize },
    [Figure.ROLL]: { text: 'ROLL', size: DSize },
    [Figure.CONT]: { text: '', size: DSize },
    [Figure.B_HALF]: { text: '0.5', size: BSize },
    [Figure.B_ONE]: { text: '1', size: BSize },
    [Figure.B_FIVE]: { text: '5', size: BSize },
    [Figure.B_TWENTYFIVE]: { text: '25', size: BSize },
    [Figure.B_HUNDRED]: { text: '100', size: BSize },
    [Figure.B_FIVE_HUNDRED]: { text: '500', size: BSize },
    [Figure.B_THOUSAND]: { text: '1000', size: BSize },
    [Figure.FULL_SCREEN]: { text: '⤢', size: BSize }
};
